extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_f3d_material_lights;
extern Lights1 bob_dl_f3d_material_002_lights;
extern Lights1 bob_dl_f3d_material_001_lights;
extern u8 bob_dl_RMGP01_3db99ee8_14_mip3_ci4[];
extern u8 bob_dl_RMGP01_3db99ee8_14_mip3_ci4_pal_rgba16[];
extern u8 bob_dl_RMGP01_9092fc13_14_mip2_ci8[];
extern u8 bob_dl_RMGP01_9092fc13_14_mip2_ci8_pal_rgba16[];
extern u8 bob_dl_Tile0637_RGB_ci8[];
extern u8 bob_dl_Tile0637_RGB_ci8_pal_rgba16[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_0[50];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_1[48];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Plane_001_mesh_layer_5_vtx_0[8];
extern Gfx bob_dl_Plane_001_mesh_layer_5_tri_0[];
extern Gfx mat_bob_dl_f3d_material[];
extern Gfx mat_revert_bob_dl_f3d_material[];
extern Gfx mat_bob_dl_f3d_material_002[];
extern Gfx mat_revert_bob_dl_f3d_material_002[];
extern Gfx mat_bob_dl_f3d_material_001[];
extern Gfx mat_revert_bob_dl_f3d_material_001[];
extern Gfx bob_dl_Plane_mesh_layer_1[];
extern Gfx bob_dl_Plane_001_mesh_layer_5[];
extern Gfx bob_dl_material_revert_render_settings[];
